"""Initial migration.

Revision ID: f3df77ec90bd
Revises: 
Create Date: 2024-10-04 10:11:38.157220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3df77ec90bd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('trend',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('phase', sa.String(length=50), nullable=False),
    sa.Column('time_horizon', sa.String(length=50), nullable=False),
    sa.Column('relevance', sa.Integer(), nullable=False),
    sa.Column('market_potential', sa.Integer(), nullable=False),
    sa.Column('likelihood', sa.Integer(), nullable=False),
    sa.Column('sustainability', sa.Integer(), nullable=False),
    sa.Column('maturity_level', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trend_categories',
    sa.Column('trend_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['trend_id'], ['trend.id'], ),
    sa.PrimaryKeyConstraint('trend_id', 'category_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trend_categories')
    op.drop_table('trend')
    op.drop_table('category')
    # ### end Alembic commands ###
